apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: partner-catalog
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/vigneshsri-tenant/partner-catalog/partner-catalog@sha256:9737e057b2d04e6f1085e521fbd1bdb439669028dfff4a45624f9c3b069cdb19
        name: my-java-springboot
        resources: {}
status: {}
